name: terraform ci

on:
  push:
    branches:
      - main

jobs:
  run-terraform:
    name: "Run Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run terraform init
        run: terraform init

      - name: Run terraform fmt
        run: terraform fmt -check --diff

      - name: Execute terraform linter
        uses: terraform-linters/setup-tflint@v1

      - name: Execute checkov
        uses: bridgecrewio/checkov-action@master
        with:
          soft_fail: true

      - name: Run terraform plan
        run: terraform plan
        env:
          az_client_id: ${{ secrets.ARM_CLIENT_ID}}
          az_client_secret: ${{ secrets.ARM_CLIENT_SECRET}}
          az_tenant_id: ${{ secrets.ARM_TENANT_ID}}
          az_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID}}
          vm_password: ${{ secrets.TF_VAR_vm_admin_password }}

      # CONFIGURAR AZURE BACKEND ANTES DISSO
      # - name: Run terraform apply
      #   run: terraform apply -auto-approve
      #   env:
      #     az_client_id: ${{ secrets.ARM_CLIENT_ID}}
      #     az_client_secret: ${{ secrets.ARM_CLIENT_SECRET}}
      #     az_tenant_id: ${{ secrets.ARM_TENANT_ID}}
      #     az_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID}}
      #     vm_password: ${{ secrets.TF_VAR_vm_admin_password }}

      # - name: Install ansible
      # - name: Execute ansible playbook
